# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ERKWB Schweiz
# email: synode@erkwb.ch
description: >- # this means to ignore newlines until "baseurl:"
  Die Evangelisch-reformierte Kirche Westminster Bekenntnisses (ERKWB) ist eine vom Staat unabhängige Kirche. Sie bezeugt das Evangelium von Jesus Christus besonders an den Orten, wo es unbekannt oder entstellt worden ist.
baseurl: "/dev" # the subpath of your site, e.g. /blog
lang: de-CH
url: "http://erkwb.ch" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: none
# github_username:  none
logo: /assets/icons/erkwb-logo.svg

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic

# plugins:
#  - jekyll-feed

# Site settings

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
